apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  master:
    disableCSRFProtection: false
    basePlugins:
    - name: kubernetes
      version: "1.30.11"
    - name: workflow-job
      version: "2.42"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.10.0"
    - name: job-dsl
      version: "1.78.1"
    - name: configuration-as-code
      version: "1.55"
    - name: kubernetes-credentials-provider
      version: "0.20"
  jenkinsAPISettings:
    authorizationStrategy: "admin"  # Set the authorization strategy
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: main
    repositoryUrl: https://github.com/anle20/Infra-elsa.git