apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: default
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
  seedJobs:
  # - id: hackathon-starter
  #   targets: "cicd/jobs/*.jenkins"
  #   description: "hackathon-starter"
  #   repositoryBranch: master
  #   repositoryUrl: https://github.com/anle20/hackathon-starter-anle.git
  - id: hackathon-app
    targets: "cicd/jobs/*.jenkins"
    description: "hackathon-app"
    repositoryBranch: master
    repositoryUrl: https://github.com/anle20/App-elsa.git
